/**
 * config.js — binary task
 * Sequences loaded from a POOL of independent hybrid-generated sequence
 * sets (task/sequences_pool/binary_*_sequences.json), one assigned per
 * participant -- see timeline-builder.js's poolIndexForParticipant. Each
 * pool member: 8 distinct prefixes x 4 repeats = 32 trials, blue_range=
 * [2,13] out of 15, values {-1,+1}. Generated by
 * task/generate_sequences_pool.py (wrapping task/generate_sequences_hybrid.py).
 *
 * Common structure lives in shared/config-base.js — this file supplies only
 * what differs for the binary task.
 */
import { buildConfig, pickTutorialExample } from '../shared/config-base.js';

// See continuous/config.js's identical comment for why import.meta.glob
// (eager, statically bundled) rather than a runtime fetch.
const poolModules = import.meta.glob(
  '../../sequences_pool/binary_*_sequences.json',
  { eager: true, import: 'default' });
const sequencesPool = Object.keys(poolModules).sort().map(k => poolModules[k]);

// Tutorial example derived from pool member 0 -- see continuous/config.js's
// identical comment for why (arbitrary but fixed, deterministic choice).
const { values: tutorialValues, mean: TUTORIAL_P } =
  pickTutorialExample(sequencesPool[0], { isBinary: true, n: 5 });

export const config = buildConfig({
  taskType:      'binary',
  sequencesPool,
  tutorialValues,
  tutorialMean:  TUTORIAL_P,
  tutorialStd:   0,
  // No overrides — binary currently uses all shared defaults.
});
