/**
 * config.js — binary task
 * Sequences loaded from task/sequences/binary_sequences.json
 * (single master copy — generated by task/generate_sequences.py)
 * p_range=0.2..0.8, values {-1,+1}
 */
import sequencesData from '../../sequences/binary_sequences.json';

// ── Parameters ────────────────────────────────────────────────────────────
const N_TRIALS_TO_RUN        = 2;       // ← SET TO 40 BEFORE DEPLOYMENT
const SHOW_SLIDER_VALUE      = true;
const SLIDER_DEFAULT         = 'none';
const DEFAULT_VALUE          = 50;      // midpoint of [0,100] slider
const ITI_MS                 = 1000;
const T_OBS_MS               = 5000;
const SHOW_TRIAL_PERFORMANCE = true;

// Practice (tutorial) — fixed sequence: B B R B R (+1=blue, -1=red)
const practiceValues = [1, 1, -1, 1, -1];  // true_p ≈ 0.6
const PRACTICE_P     = 0.6;

export const config = {
  taskType:             'binary',
  sequences:            sequencesData.slice(0, N_TRIALS_TO_RUN),
  practiceValues,
  practiceMean:         PRACTICE_P,
  practiceStd:          0,
  showSliderValue:      SHOW_SLIDER_VALUE,
  sliderDefault:        SLIDER_DEFAULT,
  defaultValue:         DEFAULT_VALUE,
  itiMs:                ITI_MS,
  tObsMs:               T_OBS_MS,
  showTrialPerformance: SHOW_TRIAL_PERFORMANCE,
};
