/**
 * config.js — binary task
 * Sequences loaded from a POOL of independent hybrid-generated sequence
 * sets (task/sequences_pool/binary_*_sequences.json), one assigned per
 * participant -- see timeline-builder.js's poolIndexForParticipant. Each
 * pool member: 8 distinct prefixes x 4 repeats = 32 trials, blue_range=
 * [2,13] out of 15, values {-1,+1}. Generated by
 * task/generate_sequences_pool.py (wrapping task/generate_sequences_hybrid.py).
 *
 * Common structure lives in shared/config-base.js — this file supplies only
 * what differs for the binary task.
 */
import { buildConfig, pickTutorialExample, DEFAULTS } from '../shared/config-base.js';

// See continuous/config.js's identical comment for why import.meta.glob
// (eager, statically bundled) rather than a runtime fetch.
const poolModules = import.meta.glob(
  '../../sequences_pool/binary_*_sequences.json',
  { eager: true, import: 'default' });
const sequencesPool = Object.keys(poolModules).sort().map(k => poolModules[k]);

// Tutorial example derived from pool member 0 -- see continuous/config.js's
// identical comment for why (arbitrary but fixed, deterministic choice).
// n: DEFAULTS.N_OBS_TO_RUN (not a second hardcoded 5, chat history) -- the
// tutorial now walks through a full real trial's worth of observations,
// matching real-task length exactly, and can never silently drift out of
// sync with N_OBS_TO_RUN again -- same fix continuous/config.js already got.
const { values: tutorialValues, mean: TUTORIAL_P } =
  pickTutorialExample(sequencesPool[0], { isBinary: true, n: DEFAULTS.N_OBS_TO_RUN });

export const config = buildConfig({
  taskType:      'binary',
  sequencesPool,
  tutorialValues,
  tutorialMean:  TUTORIAL_P,
  tutorialStd:   0,
  // ERROR_MODE override (chat history) -- binary's own errorMode values
  // are 'true_p'/'running_p', distinct strings from continuous's
  // 'true_mean'/'running_mean' -- see bonus-continuous.js's own docstring
  // for why. Set to 'running_p' here for testing, mirroring continuous's
  // own DEFAULTS.ERROR_MODE currently being 'running_mean' for the same
  // reason.
  overrides: { ERROR_MODE: 'running_p' },
});
