/**
 * config.js — continuous task
 * Sequences loaded from a POOL of independent hybrid-generated sequence
 * sets (task/sequences_pool/continuous_*_sequences.json), one assigned per
 * participant -- see timeline-builder.js's poolIndexForParticipant. Each
 * pool member: 8 distinct prefixes x 4 repeats = 32 trials, mean_range=
 * [15,85], std_fixed=15, values in [1,99] (boundary_margin=1). Generated by
 * task/generate_sequences_pool.py (wrapping task/generate_sequences_hybrid.py).
 *
 * Common structure lives in shared/config-base.js — this file supplies only
 * what differs for the continuous task.
 */
import { buildConfig, pickTutorialExample } from '../shared/config-base.js';

// Statically bundled via import.meta.glob(eager) rather than a runtime
// fetch of a pool directory -- avoids any dependency on JATOS reliably
// serving extra static assets (an unverified, real risk category this
// project has hit surprises in before -- see CLAUDE.md's "Tab-visibility
// handling" section and the urlQueryParameters fix), at a measured,
// acceptable bundle-size cost (~150KB gzip for 200 members -- smaller than
// this app's own CSS). Object keys are file paths; sorting them
// alphabetically is what makes pool index N line up with file
// continuous_{NNNN}_sequences.json -- zero-padding in the filename (see
// generate_sequences_pool.py) is exactly what makes that alphabetical sort
// equal numeric order.
const poolModules = import.meta.glob(
  '../../sequences_pool/continuous_*_sequences.json',
  { eager: true, import: 'default' });
const sequencesPool = Object.keys(poolModules).sort().map(k => poolModules[k]);

// Tutorial example is derived from a REAL trial in pool member 0 -- an
// arbitrary but fixed, deterministic choice (the tutorial just needs ONE
// representative example, not something tied to any participant's actual
// pool assignment) -- rather than hand-picked literals. See
// config-base.js's pickTutorialExample for why hand-picked examples are
// avoided: they silently drift out of sync when the pool is regenerated
// with different mean_range/std_fixed, which already happened once before
// this file used a pool at all (the tutorial's std=20 no longer matched
// the real std=15).
const { values: tutorialValues, mean: TUTORIAL_MEAN, std: TUTORIAL_STD } =
  pickTutorialExample(sequencesPool[0], { isBinary: false, n: 5 });

export const config = buildConfig({
  taskType:      'continuous',
  sequencesPool,
  tutorialValues,
  tutorialMean:  TUTORIAL_MEAN,
  tutorialStd:   TUTORIAL_STD,
  // No overrides — continuous currently uses all shared defaults.
});
