/**
 * config.js — continuous task
 * Sequences loaded from task/sequences/continuous_sequences.json
 * (single master copy — generated by task/generate_sequences.py)
 * mean_range=20..80, std_fixed=20, values in [0,100]
 */
import sequencesData from '../../sequences/continuous_sequences.json';

// ── Parameters ────────────────────────────────────────────────────────────
// Set TEST_MODE=true for quick dev runs: skip/take tutorial, 20 trials, 500ms BTI
const TEST_MODE              = false;

const N_TRIALS_TO_RUN        = TEST_MODE ? 20  : 24;  // 6 seqs × 4 reps
const N_OBS_TO_RUN           = 15;
const SHOW_SLIDER_VALUE      = true;    // float label above thumb
const SLIDER_DEFAULT         = 'none';  // 'none' | 'last'
const DEFAULT_VALUE          = 50;      // midpoint of [0, 100]
const DEBUG_FAST = false;   // set true for fast automated testing only
const BTI_MS             = TEST_MODE ? 500  : 3000;
const ITI_SHORT_MS       = 1000;
const T_OBS_MS           = 7000;
const SHOW_TRIAL_PERFORMANCE = true;
const DISTRACTOR_TYPE        = 'none';  // 'none' | 'iti_length' | 'popup'

// ── Practice (tutorial) ───────────────────────────────────────────────────
// Fixed sequence: 5 values drawn from Normal(20, 25), all within 1σ of mean,
// at least 2 above and 2 below true_mean for pedagogical clarity.
// Generated with seed=5 of the constrained sampler.
const PRACTICE_MEAN = 60;
const PRACTICE_STD  = 20;  // matches experiment std_fixed=20
const practiceValues = [48, 75, 38, 82, 57];  // mean≈60, spread ≈ std=20

export const config = {
  taskType:             'continuous',
  sequences:            sequencesData.map(
                          s => ({ ...s, values: s.values.slice(0, N_OBS_TO_RUN) })
                        ),
  nTrialsDefault:       N_TRIALS_TO_RUN,  // used by buildAndRun when no override
  practiceValues,
  practiceMean:         PRACTICE_MEAN,
  practiceStd:          PRACTICE_STD,
  showSliderValue:      SHOW_SLIDER_VALUE,
  sliderDefault:        SLIDER_DEFAULT,
  defaultValue:         DEFAULT_VALUE,
  btiMs:               BTI_MS,
  itiShortMs:         ITI_SHORT_MS,
  tObsMs:               T_OBS_MS,
  showTrialPerformance: SHOW_TRIAL_PERFORMANCE,
  distractorType:       DISTRACTOR_TYPE,
  testMode:             TEST_MODE,
};
