#!/usr/bin/env python3
"""
Copy NEF (recurrent)'s already-fitted per-pid params into a placeholder
NEF_synaptic run folder, so preliminary experiments (e.g. an ITI-noise
manipulation comparing the two nef_type branches) can run against
NEF_synaptic before its own Optuna RMSE fit exists -- that fit takes days;
this is a stopgap, not a substitute.

Writes ONLY {model_type}_{stem}_{pid}_params.pkl files -- no
_performance.pkl/_folds.pkl/_responses.pkl, since those describe NEF
(recurrent)'s own achieved loss and simulated output, which would be
actively misleading under an NEF_synaptic filename (implies NEF_synaptic
was evaluated and scored, when it has not been). No combined
{model_type}_{stem}_params.pkl either -- fitting.collect needs a
run_config.json job manifest that only fitting.submit produces, and
nothing downstream needs the combined file (utils.run_params.load_run_params
reads per-pid files directly).

Source pid list comes from each dataset's own data/{dataset}.pkl (the
authoritative pid roster), not from globbing filenames in the source run
folder -- avoids the exact hazard CLAUDE.md's "What NOT to do" flags for
globbed pid patterns across dataset stems that share a prefix (e.g.
soltani_numbers/soltani_colors).

Usage:
    venv/bin/python scripts/copy_nef_synaptic_placeholder.py
"""

from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from utils.paths import RUNS_DIR, data_path, resolve_run_folder

SOURCE_MODEL_TYPE = "NEF"
TARGET_MODEL_TYPE = "NEF_synaptic"
SOURCE_RUN_FOLDER = "rmse"
TARGET_RUN_FOLDER = "synaptic_placeholder"
DATASETS = ("carrabin", "yoo", "soltani_numbers", "soltani_colors")

PLACEHOLDER_NOTE = """\
# NEF_synaptic placeholder params

Every `{model}_{{dataset}}_{{pid}}_params.pkl` file in this folder is a
COPY of NEF (recurrent)'s own already-fitted (alpha_0, lambda_) for that
pid, relabelled `model_type={model}` -- NOT an independent NEF_synaptic
fit. NEF_synaptic has never been evaluated against human data with these
params; they exist only so a preliminary experiment (e.g. the ITI-noise
manipulation) can simulate NEF_synaptic at SOME reasonable params before
its own Optuna RMSE fit completes (that fit takes days -- see chat).

Each file has a `placeholder_source` column recording this.

Delete this folder and regenerate any downstream results once a real
per-pid NEF_synaptic fit exists in `data/runs/rmse/`.

Generated by `scripts/copy_nef_synaptic_placeholder.py`.
""".format(model=TARGET_MODEL_TYPE)


def main() -> None:
    source_dir = resolve_run_folder(SOURCE_RUN_FOLDER)
    target_dir = RUNS_DIR / TARGET_RUN_FOLDER
    target_dir.mkdir(parents=True, exist_ok=True)

    for dataset in DATASETS:
        human = pd.read_pickle(data_path(f"{dataset}.pkl"))
        pids = sorted(int(p) for p in human["pid"].unique())
        n_copied = 0
        missing: list[int] = []
        for pid in pids:
            src = source_dir / f"{SOURCE_MODEL_TYPE}_{dataset}_{pid}_params.pkl"
            if not src.exists():
                missing.append(pid)
                continue
            df = pd.read_pickle(src).copy()
            df["model_type"] = TARGET_MODEL_TYPE
            df["placeholder_source"] = SOURCE_MODEL_TYPE
            dst = target_dir / f"{TARGET_MODEL_TYPE}_{dataset}_{pid}_params.pkl"
            df.to_pickle(dst)
            n_copied += 1
        print(f"{dataset}: copied {n_copied}/{len(pids)} pids"
              + (f" (missing NEF fit for pids {missing})" if missing else ""))

    (target_dir / "PLACEHOLDER.md").write_text(PLACEHOLDER_NOTE)
    print(f"\nWrote placeholder params + PLACEHOLDER.md to {target_dir}")


if __name__ == "__main__":
    main()
