/**
 * config.js — numbers task
 * Sequences loaded from the consolidated pool file
 * (task_backend/sequences_numbers.json) -- a single JSON array of 200
 * independent pool members, one assigned per participant (see
 * timeline-builder.js's poolIndexForParticipant). Each pool member: 8
 * distinct prefixes x 4 repeats = 32 trials, values in [1,99]
 * (boundary_margin=1); mean_range/std_fixed are NOT repeated here as
 * literals -- see task_backend/generate_sequences.py's own
 * NUMBERS_MEAN_RANGE/NUMBERS_STD_FIXED constants for the current values
 * (deliberately not duplicated in a comment here again -- a duplicated
 * literal is exactly what let std_fixed silently drift out of sync once
 * already, see docs/HISTORY.md). Generated by
 * task_backend/generate_sequences.py.
 *
 * TEST VARIANTS: set VITE_SEQUENCES_VARIANT (in .env, or inline before a
 * command, e.g. `VITE_SEQUENCES_VARIANT=test2trial npm run dev:numbers`)
 * to load sequences_numbers_<variant>.json instead -- e.g. a small
 * 2-trial pool from `python generate_sequences.py --name test2trial`,
 * for a full end-to-end session in seconds/minutes instead of ~15-30
 * minutes. import.meta.glob auto-discovers ANY matching file, so a new
 * test variant never requires editing this file -- generate it, set the
 * env var, done. Unset (or empty) VITE_SEQUENCES_VARIANT -> the real
 * production pool, unaffected by this mechanism existing at all.
 *
 * Common structure lives in shared/config-base.js — this file supplies only
 * what differs for the numbers task.
 */
import { buildConfig, DEFAULTS } from '../shared/config-base.js';
import tutorialSequence from '../../tutorial_sequence_numbers.json';

// Vite requires import.meta.glob's pattern to be a literal string it can
// statically analyze at THIS call site -- can't factor this into a
// shared helper taking the pattern as a parameter (see colors/config.js
// for the near-identical, unavoidably duplicated counterpart).
const sequenceModules = import.meta.glob('../../sequences_numbers*.json', { eager: true });
const variant = import.meta.env.VITE_SEQUENCES_VARIANT;
const fileKey = variant ? `../../sequences_numbers_${variant}.json` : '../../sequences_numbers.json';
if (!sequenceModules[fileKey]) {
  throw new Error(
    `No sequences file found for key "${fileKey}" (VITE_SEQUENCES_VARIANT=${variant ?? '(unset)'}). ` +
    `Available: ${Object.keys(sequenceModules).join(', ')}`
  );
}
const sequencesPool = sequenceModules[fileKey].default;

// Tutorial example: ONE fixed trial, the SAME for every participant
// regardless of their own pool assignment -- generated (not hand-picked)
// by task_backend/generate_sequences.py's choose_tutorial_sequences,
// which searches the whole real production pool for a trial with a
// genuinely large early swing in the running mean (first 5 observations)
// while still keeping the rest of the trial visibly moving too (see that
// function's own docstring for the exact two-stage selection criterion).
// Regenerate via `python generate_sequences.py --tutorial` if the
// production pool is ever rebuilt with a different design -- this file
// is a plain, non-variant JSON snapshot, so it does NOT participate in
// the VITE_SEQUENCES_VARIANT mechanism above; the tutorial always walks
// through the same fixed example regardless of which sequences pool
// variant is loaded.
//
// tutorialValues is sliced to DEFAULTS.N_OBS_TO_RUN (not a second
// hardcoded 15) for the same reason the old pickTutorialExample-based
// version was: the tutorial walks through a full real trial's worth of
// observations, so participants see the estimate genuinely accumulate
// over the same number of observations as a real trial, not a truncated
// preview of it. true_std is the trial's own recorded value (the
// generative std_fixed constant, not a re-derived empirical estimate --
// see generate_numbers_trials, which stores this directly on every trial).
const tutorialValues = tutorialSequence.values.slice(0, DEFAULTS.N_OBS_TO_RUN);
const TUTORIAL_MEAN = tutorialSequence.true_mean;
const TUTORIAL_STD = tutorialSequence.true_std;

export const config = buildConfig({
  taskType:      'numbers',
  sequencesPool,
  tutorialValues,
  tutorialMean:  TUTORIAL_MEAN,
  tutorialStd:   TUTORIAL_STD,
  // No overrides — numbers currently uses all shared defaults.
});
