/**
 * config.js — numbers task
 * Sequences loaded from the consolidated pool file
 * (task_backend/sequences_numbers.json) -- a single JSON array of 200
 * independent pool members, one assigned per participant (see
 * timeline-builder.js's poolIndexForParticipant). Each pool member: 8
 * distinct prefixes x 4 repeats = 32 trials, mean_range=[15,85],
 * std_fixed=10, values in [1,99] (boundary_margin=1). Generated by
 * task_backend/generate_sequences.py.
 *
 * TEST VARIANTS: set VITE_SEQUENCES_VARIANT (in .env, or inline before a
 * command, e.g. `VITE_SEQUENCES_VARIANT=test2trial npm run dev:numbers`)
 * to load sequences_numbers_<variant>.json instead -- e.g. a small
 * 2-trial pool from `python generate_sequences.py --name test2trial`,
 * for a full end-to-end session in seconds/minutes instead of ~15-30
 * minutes. import.meta.glob auto-discovers ANY matching file, so a new
 * test variant never requires editing this file -- generate it, set the
 * env var, done. Unset (or empty) VITE_SEQUENCES_VARIANT -> the real
 * production pool, unaffected by this mechanism existing at all.
 *
 * Common structure lives in shared/config-base.js — this file supplies only
 * what differs for the numbers task.
 */
import { buildConfig, pickTutorialExample, DEFAULTS } from '../shared/config-base.js';

// Vite requires import.meta.glob's pattern to be a literal string it can
// statically analyze at THIS call site -- can't factor this into a
// shared helper taking the pattern as a parameter (see colors/config.js
// for the near-identical, unavoidably duplicated counterpart).
const sequenceModules = import.meta.glob('../../sequences_numbers*.json', { eager: true });
const variant = import.meta.env.VITE_SEQUENCES_VARIANT;
const fileKey = variant ? `../../sequences_numbers_${variant}.json` : '../../sequences_numbers.json';
if (!sequenceModules[fileKey]) {
  throw new Error(
    `No sequences file found for key "${fileKey}" (VITE_SEQUENCES_VARIANT=${variant ?? '(unset)'}). ` +
    `Available: ${Object.keys(sequenceModules).join(', ')}`
  );
}
const sequencesPool = sequenceModules[fileKey].default;

// Tutorial example is derived from a REAL trial in pool member 0 -- an
// arbitrary but fixed, deterministic choice (the tutorial just needs ONE
// representative example, not something tied to any participant's actual
// pool assignment) -- rather than hand-picked literals. See
// config-base.js's pickTutorialExample for why hand-picked examples are
// avoided: they silently drift out of sync when the pool is regenerated
// with different mean_range/std_fixed.
//
// n: DEFAULTS.N_OBS_TO_RUN (not a second hardcoded 15) -- the tutorial
// walks through a full real trial's worth of observations, so participants
// see the estimate genuinely accumulate over the same number of
// observations as a real trial, not a truncated preview of it.
const { values: tutorialValues, mean: TUTORIAL_MEAN, std: TUTORIAL_STD } =
  pickTutorialExample(sequencesPool[0], { isColors: false, n: DEFAULTS.N_OBS_TO_RUN });

export const config = buildConfig({
  taskType:      'numbers',
  sequencesPool,
  tutorialValues,
  tutorialMean:  TUTORIAL_MEAN,
  tutorialStd:   TUTORIAL_STD,
  // No overrides — numbers currently uses all shared defaults.
});
