/**
 * config.js — numbers task
 * Sequences loaded from the consolidated pool file
 * (task_backend/sequences_numbers.json) -- a single JSON array of 200
 * independent pool members, one assigned per participant (see
 * timeline-builder.js's poolIndexForParticipant). Each pool member: 8
 * distinct prefixes x 4 repeats = 32 trials, mean_range=[15,85],
 * std_fixed=10, values in [1,99] (boundary_margin=1). Generated by
 * task_backend/generate_sequences.py.
 *
 * Common structure lives in shared/config-base.js — this file supplies only
 * what differs for the numbers task.
 */
import { buildConfig, pickTutorialExample, DEFAULTS } from '../shared/config-base.js';

// Statically bundled via a direct JSON import rather than the old
// import.meta.glob-over-400-files-then-sort approach -- generate_sequences.py
// now writes the WHOLE pool as one file, so the array is already in pool-
// index order (index i IS pool member i); nothing to glob or sort here.
import sequencesPool from '../../sequences_numbers.json';

// Tutorial example is derived from a REAL trial in pool member 0 -- an
// arbitrary but fixed, deterministic choice (the tutorial just needs ONE
// representative example, not something tied to any participant's actual
// pool assignment) -- rather than hand-picked literals. See
// config-base.js's pickTutorialExample for why hand-picked examples are
// avoided: they silently drift out of sync when the pool is regenerated
// with different mean_range/std_fixed.
//
// n: DEFAULTS.N_OBS_TO_RUN (not a second hardcoded 15) -- the tutorial
// walks through a full real trial's worth of observations, so participants
// see the estimate genuinely accumulate over the same number of
// observations as a real trial, not a truncated preview of it.
const { values: tutorialValues, mean: TUTORIAL_MEAN, std: TUTORIAL_STD } =
  pickTutorialExample(sequencesPool[0], { isColors: false, n: DEFAULTS.N_OBS_TO_RUN });

export const config = buildConfig({
  taskType:      'numbers',
  sequencesPool,
  tutorialValues,
  tutorialMean:  TUTORIAL_MEAN,
  tutorialStd:   TUTORIAL_STD,
  // No overrides — numbers currently uses all shared defaults.
});
