/**
 * config.js — colors task
 * Sequences loaded from the consolidated pool file
 * (task_backend/sequences_colors.json) -- a single JSON array of 200
 * independent pool members, one assigned per participant (see
 * timeline-builder.js's poolIndexForParticipant). Each pool member: 32
 * fully independent trials (no prefix/repeat structure), blue_range=[2,13]
 * out of 15, values {-1,+1}. Generated by task_backend/generate_sequences.py.
 *
 * Common structure lives in shared/config-base.js — this file supplies only
 * what differs for the colors task.
 */
import { buildConfig, pickTutorialExample, DEFAULTS } from '../shared/config-base.js';

// See numbers/config.js's identical comment for why this is a direct
// JSON import rather than a glob-and-sort over per-member files.
import sequencesPool from '../../sequences_colors.json';

// Tutorial example derived from pool member 0 -- see numbers/config.js's
// identical comment for why (arbitrary but fixed, deterministic choice).
const { values: tutorialValues, mean: TUTORIAL_P } =
  pickTutorialExample(sequencesPool[0], { isColors: true, n: DEFAULTS.N_OBS_TO_RUN });

export const config = buildConfig({
  taskType:      'colors',
  sequencesPool,
  tutorialValues,
  tutorialMean:  TUTORIAL_P,
  tutorialStd:   0,
  // ERROR_MODE override -- colors's own errorMode values are
  // 'true_p'/'running_p', distinct strings from numbers's
  // 'true_mean'/'running_mean' -- see scoring.js's own docstring
  // for why. Set to 'running_p' here, mirroring numbers's own
  // DEFAULTS.ERROR_MODE currently being 'running_mean' for the same reason.
  overrides: { ERROR_MODE: 'running_p' },
});
